export const ACTIVITIES_LIST_REQUEST = "ACTIVITIES_LIST_REQUEST";
export const ACTIVITIES_LIST_SUCCESS = "ACTIVITIES_LIST_SUCCESS";
export const ACTIVITIES_LIST_FAIL = "ACTIVITIES_LIST_FAIL";

export const ACTIVITIES_DETAILS_REQUEST = "ACTIVITIES_DETAILS_REQUEST";
export const ACTIVITIES_DETAILS_SUCCESS = "ACTIVITIES_DETAILS_SUCCESS";
export const ACTIVITIES_DETAILS_FAIL = "ACTIVITIES_DETAILS_FAIL";

export const ACTIVITIES_DELETE_REQUEST = "ACTIVITIES_DELETE_REQUEST";
export const ACTIVITIES_DELETE_SUCCESS = "ACTIVITIES_DELETE_SUCCESS";
export const ACTIVITIES_DELETE_FAIL = "ACTIVITIES_DELETE_FAIL";

export const ACTIVITIES_CREATE_REQUEST = "ACTIVITIES_CREATE_REQUEST";
export const ACTIVITIES_CREATE_SUCCESS = "ACTIVITIES_CREATE_SUCCESS";
export const ACTIVITIES_CREATE_FAIL = "ACTIVITIES_CREATE_FAIL";
export const ACTIVITIES_CREATE_RESET = "ACTIVITIES_CREATE_RESET";

export const ACTIVITIES_UPDATE_REQUEST = "ACTIVITIES_UPDATE_REQUEST";
export const ACTIVITIES_UPDATE_SUCCESS = "ACTIVITIES_UPDATE_SUCCESS";
export const ACTIVITIES_UPDATE_FAIL = "ACTIVITIES_UPDATE_FAIL";
export const ACTIVITIES_UPDATE_RESET = "ACTIVITIES_UPDATE_RESET";

