<<<<<<< HEAD
export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL";
export const PROFILE_UPDATE_RESET = "PROFILE_UPDATE_RESET";

export const PROFILE_DETAILS_REQUEST = "PROFILE_DETAILS_REQUEST";
export const PROFILE_DETAILS_SUCCESS = "PROFILE_DETAILS_SUCCESS";
export const PROFILE_DETAILS_FAIL = "PROFILE_DETAILS_FAIL";

export const PROFILE_DETAILSONE_REQUEST = "PROFILE_DETAILSONE_REQUEST";
export const PROFILE_DETAILSONE_SUCCESS = "PROFILE_DETAILSONE_SUCCESS";
export const PROFILE_DETAILSONE_FAIL = "PROFILE_DETAILSONE_FAIL";


export const PROFILE_DELETE_TECHNOLOGIES_REQUEST =
  "PROFILE_DELETE_TECHNOLOGIES_REQUEST";
export const PROFILE_DELETE_TECHNOLOGIES_SUCCESS =
  "PROFILE_DELETE_TECHNOLOGIES_SUCCESS";
export const PROFILE_DELETE_TECHNOLOGIES_FAIL = "PROFILE_DELETE_TECHNOLOGIES_FAIL";


export const PROFILE_CREATE_TECHNOLOGIES_REQUEST =
  "PROFILE_CREATE_TECHNOLOGIES_REQUEST";
export const PROFILE_CREATE_TECHNOLOGIES_SUCCESS =
  "PROFILE_CREATE_TECHNOLOGIES_SUCCESS";
export const PROFILE_CREATE_TECHNOLOGIES_FAIL = "PROFILE_CREATE_TECHNOLOGIES_FAIL";
export const PROFILE_CREATE_TECHNOLOGIES_RESET = "PROFILE_CREATE_TECHNOLOGIES_RESET";
=======
export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAIL = 'PROFILE_FAIL'
>>>>>>> upstream/main
